# Generated by Django 5.0.1 on 2024-02-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='image_logo/', verbose_name='Логотип')),
                ('name', models.CharField(max_length=255, verbose_name='Имя ')),
                ('work', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Основная Настройка',
                'verbose_name_plural': 'Основные Настройки',
            },
        ),
    ]
