# Generated by Django 5.0.1 on 2024-02-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Об о мне',
                'verbose_name_plural': 'Об о мне',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': '1) Основная Настройка', 'verbose_name_plural': '1) Основные Настройки'},
        ),
    ]
