# Generated by Django 5.0.1 on 2024-02-05 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_catigory_alter_about_options_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '5) Проект', 'verbose_name_plural': '5) Проекты'},
        ),
        migrations.AddField(
            model_name='products',
            name='catigory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.catigory', verbose_name='Выбрать категорию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='image_producrs/', verbose_name='Фотграфия'),
        ),
    ]
