# Generated by Django 5.0.1 on 2024-02-05 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_products_options_products_catigory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Скил',
                'verbose_name_plural': 'Скилы',
            },
        ),
        migrations.CreateModel(
            name='SkillsPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.CharField(max_length=255, verbose_name='процент')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_title', to='base.skills')),
            ],
            options={
                'unique_together': {('skills', 'percent')},
            },
        ),
    ]
