# Generated by Django 5.0.1 on 2024-02-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_skills_skillspercent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillspercent',
            old_name='title',
            new_name='title1',
        ),
    ]
