# Generated by Django 5.0.1 on 2024-02-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_title_skillspercent_title1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(verbose_name='Видео')),
            ],
            options={
                'verbose_name': '7) Видео',
                'verbose_name_plural': '7) Видео',
            },
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': '6) Скил', 'verbose_name_plural': '6) Скилы'},
        ),
    ]
