# Generated by Django 5.0.1 on 2024-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_video_alter_skills_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=1, upload_to='image_back', verbose_name='Фотография background'),
            preserve_default=False,
        ),
    ]
