# Generated by Django 5.0.1 on 2024-02-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Парнер',
                'verbose_name_plural': 'Парнеры',
            },
        ),
    ]
