# Generated by Django 5.0.1 on 2024-02-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('work', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='image_review/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': '9) Отзыв',
                'verbose_name_plural': '9) Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': '8) Парнер', 'verbose_name_plural': '8) Парнеры'},
        ),
    ]
