# Generated by Django 5.0.1 on 2024-02-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_settings_address_settings_facebook_settings_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Project',
        ),
    ]
