# Generated by Django 5.0.1 on 2024-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_products_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='image_products/', verbose_name='Фотграфия'),
        ),
    ]
