# Generated by Django 5.0.1 on 2024-02-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catigory',
            old_name='catigory_amount',
            new_name='catigory',
        ),
    ]
